[feature/MOB-560] Magic link login
Aptoide/aptoide-uploader pull request #31
Opened 2020-06-15 11:37 UTC by franciscoaleixo

**What does this PR do?**

   Adds support for magic link login.

**How should this be manually tested?**

  Check the same flows as vanilla for logging in with magic link.

**What are the relevant tickets?**

  [MOB-560](https://aptoide.atlassian.net/browse/MOB-560)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional tests pass

2020-06-17 18:01 UTC, phillipsgoncalves requested changes
Also regarding the strings, is everything ok with carlos ?

Also, clicking on the secure message is not navigating to the blog. Was it supposed to?

2020-06-17 18:01 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/UploaderApplication.java
> +    return new AptoideAuthenticationRx(new AptoideAuthentication(
This is only used on one place but should we put it as singleton for prevention or not worth it ?

2020-06-17 18:01 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/account/AccountValidationException.java
> +  // TODO: 6/4/20 I replaced one that was alone with the empty store add it in case needed.
todo note

2020-06-17 18:01 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/account/AptoideAccountManager.java
> +    // TODO: 6/4/20 one error we had on vanilla was the fact that
todo comment again

2020-06-17 18:01 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/account/AptoideAccountManager.java
> +    // TODO: 6/4/20 commented this validation in order to not have to change the call of this method as it is going to probably be removed?
Todo comment again. 
Also, this is related to a validation that was being done before and is not being done now. Was this validated with John ?

2020-06-17 18:01 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/account/CredentialsValidator.java
>    public Completable validate(String email, String password, String storeName) {
Related with the previous comment. This validation was commented, does it need to be done? Was this validated with joao

2020-06-17 18:01 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/account/network/RetrofitAccountService.java
> +    this.aptoideAuthentication = aptoideAuthentication;
There is code in this class still related with the old login, like the createAccountMethod that has null password and storename being passed to it, which is being used in createAccount presenter, which is not being really used anymore i think.
Remove the rest of unused code

2020-06-17 18:01 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/account/view/AccountErrorMapper.java
> +      /*case AccountValidationException.EMPTY_PASSWORD:
commented code related with the previously mentioned verification

2020-06-17 18:01 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/account/view/LoginPresenter.java
> -        .doOnNext(__ -> loginNavigator.openBlogUrl())
This was removed, so this method on login navigator is not being used anymore

2020-06-18 10:01 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/account/AptoideAccountManager.java
> +    // TODO: 6/4/20 commented this validation in order to not have to change the call of this method as it is going to probably be removed?
Removed this and their usage.

2020-06-18 14:52 UTC, merged