Bugfix/mob 306 backgroud service upload
Aptoide/aptoide-uploader pull request #32
Opened 2020-06-25 12:52 UTC by danfbfern

**What does this PR do?**

   Allows uploads to be done in the background after the application is closed

**Where should the reviewer start?**

- NotificationApplicationView.java
- UploadManager.java
- NotificationPresenter.java
- MemoryDraftPersistence.java

**How should this be manually tested?**

 Open Uploader, start an upload, close the application process after the notification shows up and check if the upload progress continues

**What are the relevant tickets?**

  https://aptoide.atlassian.net/browse/MOB-306

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional tests pass

2020-06-26 10:12 UTC, franciscoaleixo requested changes

2020-06-26 10:12 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/NotificationApplicationView.java
> +public class NotificationApplicationView extends Service implements NotificationView {
This should probably be renamed since it is now a service (e.g. NotificationService?)

2020-06-26 10:12 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/NotificationApplicationView.java
> +    Log.i("LOL", "Service has been started onCreate");
These logs should either be removed or moved to "Log.d" so they only appear on debug versions. Also you might want to change the tag name from "LOL" to something more meaningful 🦺

2020-06-26 10:12 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/UploaderService.java
> +/*
Commented file, can be removed.

2020-06-26 10:12 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/apps/ServiceBackgroundService.java
> +    Log.i("LOL", "Going to disable the service");
^ Same log comment

2020-06-26 10:12 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/apps/UploadManager.java
> +            "handleBackgroundService: after getDrafts " + draftList.size()))
^ Same logs comment in this class.

2020-06-26 10:12 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/apps/view/NotificationPresenter.java
> +        .doOnNext(lifecycleEvent -> Log.d("LOL",
^ Same logs comment in this class

2020-06-26 10:14 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/UploaderApplication.java
> -public class UploaderApplication extends NotificationApplicationView {
Code style missing

2020-06-26 10:15 UTC, franciscoaleixo requested changes

2020-06-26 10:15 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/UploaderApplication.java
> +public class UploaderApplication extends Application {
Code style missing

2020-06-26 10:15 UTC, franciscoaleixo commented on app/src/main/java/com/aptoide/uploader/apps/StoreManager.java
> +import io.reactivex.internal.operators.completable.CompletableFromAction;
Code style

2020-07-03 15:54 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/apps/StoreManager.java
> +            .flatMapCompletable(languageCode -> startService().andThen(Observable.fromIterable(apps)
maybe this startservice stopped being necessary as we started using the chain handleBackgroundService

2020-07-03 15:57 UTC, phillipsgoncalves commented
Tested and it is ok

2020-07-06 10:52 UTC, merged