[Feature/APP-84] Auto Upload
Aptoide/aptoide-uploader pull request #46
Opened 2021-04-08 09:44 UTC by danfbfern

**What does this PR do?**

   Adds autoupload feature to the uploader. 
   - Tooltip on first time app is laucnhed
   - Settings screen 
   - Auto upload screen with list to select the apps
   Service works in the background, when an app is updated and is from the selected list, the upload will start. 

**Where should the reviewer start?**

- InstallManager.kt
- AutoUploadSelectsManager.kt
- InstalledAppsManager.java
- AutoUploadPresenter.java
- SettingsPresenter.java

**How should this be manually tested?**

- Install an older version of an app from the Aptoide store
- Open Uploader and navigate to the autoupload (login -> myapps -> settings -> autoupload)
- Select the app that was installed. 
- Go back to vanilla and select a version of the app to update to.
- Check the notification of the upload after the new version was installed.

- Check on the seetings view, if the selected app image is shown.
- Select more apps (if 3 or less are selected, all images will show. if more than 3 are selected, 3 of them will show and the rest will be a number)

**What are the relevant tickets?**

  https://aptoide.atlassian.net/browse/APP-84

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional tests pass

2021-08-12 01:11 UTC, phillipsgoncalves requested changes

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/UploaderApplication.java
> +  public RoomInstalledPersistence getInstalledPersistence() {
Should use the interface instead of the RoomPersistence class

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/UploaderApplication.java
> +  public RoomAutoUploadSelectsPersistence getAutoUploadSelectsPersistence() {
same as above

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/account/AptoideAccountManager.java
> +            newAccount -> AccountFactory.of(true, true, storeName, newAccount.getLoginType(), null))
why null here, you could get avatar path from the newAccount object

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/apps/AutoUploadSelects.java
> +  @ColumnInfo(name = "isSelectedAutoUpload") private boolean isSelectedAutoUpload;
did this needed to go to the db?

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/apps/InstallManager.kt
> +  private fun uploadApp(installed: InstalledApp): Completable {
I would do the upload outside of the install manager

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/apps/InstalledAppsManager.java
> +  private Observable<List<InstalledApp>> getInstalledAppsPersistence() {
i woudl rename these methods as it seems like you are getting the persistence and not the apps

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/apps/InstalledAppsStatus.java
> +  public List<InstalledApp> getApps() {
would rename to getInstalledApps

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/apps/PackageManagerInstalledAppsProvider.java
> +    return getInstalledApps().flatMapObservable(apps -> Observable.fromIterable(apps))
could use flatmap iterable and then toObservable

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/apps/UploadManager.java
> +                    .doOnNext(appUploadStatuses -> Log.d("nzxt",
log to delete

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/apps/view/AutoUploadFragment.java
> +    //recyclerView.setAdapter(null);
comments

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/java/com/aptoide/uploader/apps/view/SettingsFragment.java
> +    //storeNameText = null;
comments

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/res/drawable/settings_border_background.xml
> +      <solid android:color="#e5e5e5" />
these colors should be extrracted

2021-08-12 01:11 UTC, phillipsgoncalves commented on app/src/main/res/layout/item_app_auto_upload.xml
> +        android:text="Auto upload"
should this be hardcoded ?

2021-09-14 14:16 UTC, jdandrade approved these changes

2021-09-14 14:16 UTC, merged